@Api_HostAddress = http://localhost:5238

### Get all animals
GET {{Api_HostAddress}}/api/animals
Accept: application/json

### POST - Crear un animal con imágenes (multipart/form-data)
POST {{Api_HostAddress}}/api/animals
Content-Type:  multipart/form-data; boundary=AnimalBoundary

--AnimalBoundary
Content-Disposition: form-data; name="animalData"
Content-Type: application/json

{
    "ownerId": "c74ec0e3-e3fd-4ca6-a1b7-a0f41b5ac070",
    "name": "Cocora",
    "age": 1,
    "breed": "Siames",
    "type": "gato"
}

--AnimalBoundary
Content-Disposition: form-data; name="Images"; filename="gato1.jpg"
Content-Type: image/png

 < ./wallpaperTest.png

--AnimalBoundary-- 



###
